param(
    [Parameter(Mandatory)]
    [string]$EtlFile,

    [Parameter(Mandatory)]
    [string]$OutputBase
)

$ErrorActionPreference = "Continue"

# Use tracerpt to generate CSV and summary
Write-Host "=== Using tracerpt to dump all events ==="
$csvOut = "$OutputBase`_events.csv"
$rptOut = "$OutputBase`_events.xml"

& tracerpt "$EtlFile" -o "$rptOut" -of CSV -lr 2>&1 | Out-Null

# Check if CSV was generated
if (Test-Path $csvOut) {
    $lines = (Get-Content $csvOut | Measure-Object -Line).Lines
    Write-Host "CSV file: $csvOut ($lines lines)"

    # Look for GC events
    $gcLines = Select-String -Path $csvOut -Pattern "GC" -SimpleMatch
    Write-Host "Lines containing 'GC': $($gcLines.Count)"

    # Look for CLR events
    $clrLines = Select-String -Path $csvOut -Pattern "DotNETRuntime|CLR|clr" -SimpleMatch
    Write-Host "Lines containing 'CLR/DotNET': $($clrLines.Count)"
} else {
    Write-Host "No CSV generated by tracerpt"
}

# Alternative: use xperf to dump ALL events (no provider filter) and grep for GC
Write-Host ""
Write-Host "=== Dumping all events with xperf ==="
$allOut = "$OutputBase`_alldump.txt"

# Just dump events, grep for GC-related event IDs
$xperfExe = (Get-Command xperf.exe -ErrorAction SilentlyContinue).Source
if (-not $xperfExe) { $xperfExe = "xperf.exe" }
& $xperfExe -i "$EtlFile" -a dumper 2>&1 | Select-String "GC|Heap|Alloc" | Select-Object -First 50 | Out-File -FilePath "$OutputBase`_gc_filtered.txt" -Encoding UTF8

$filteredSize = (Get-Item "$OutputBase`_gc_filtered.txt").Length
Write-Host "Filtered output: $filteredSize bytes"

if ($filteredSize -gt 0) {
    Write-Host ""
    Write-Host "=== GC-Related Events (first 50) ==="
    Get-Content "$OutputBase`_gc_filtered.txt" -Head 50
}

# Also try: dump CLR provider events using the provider name
Write-Host ""
Write-Host "=== Trying xperf with provider name ==="
$xperfExe = (Get-Command xperf.exe -ErrorAction SilentlyContinue).Source
if (-not $xperfExe) { $xperfExe = "xperf.exe" }  # assume on PATH
$providerDump = & $xperfExe -i "$EtlFile" -a dumper "-provider" "Microsoft-Windows-DotNETRuntime" 2>&1 | Select-Object -Head 30
Write-Host $providerDump
